toss/slash

- packages/react/use-ref-effect/src/index.ts
ISSUE CLOSED: #10
불필요한 index 페이지가 @toss/use-ref-effect에 있어서 @tossdocs-ignore 했습니다.
> docs: ignore tossdocs on unnecessary index.ts on @toss/use-ref-effect

- README-ko_kr.md
- README.md
1. 한국어 README.md에 존재하는 잘못된 공백을 정정합니다(`토스팀원이` -> `토스 팀원이`).
2. 각 언어별 README.md 문서 하단에 있는 토스 로고에는 `style="margin-top: 10px"` 속성이 부여되어 있지만, [HTML 변환 과정에서 제거되기 때문에](https://github.com/github/markup#github-markup) 스타일이 실제로 적용되고 있지는 않습니다. 해당 속성을 제거합니다.
3. 토스 로고를 눌렀을 때, 토스 웹사이트로 이동할 수 있도록 합니다.
4. **[토스 브랜드 아이덴티티 가이드라인](https://brand.toss.im)에 따라, 현재 다크 테마 적용 여부에 따라 다른 스타일의 토스 로고가 표시되도록 합니다.**
- GitHub 에서는 이미지 `src` 속성에 `#gh-light-mode-only` 또는 `#gh-dark-mode-only` 를 추가하는 방식을 통해 [해당 요소가 표시되는 테마를 제한](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown)하는 기능이 있습니다.
- 이 기능을 사용하면, 다크 테마에서는 배경색과 구별되는 흰색 텍스트를 가지는 `logo-toss-reverse.png` 로고가 표시되도록 할 수 있습니다. 
- 하지만 여기에는 VSCode 의 기본 마크다운 프리뷰에서는 동작하지 않는 문제가 있었습니다.
- 또한, 이미지 요소가 링크로 감싸져 있을 경우, 상위 `a` 태그의 `href` 속성을 통해 해당 값을 …
> docs: Show reversed Toss logo on dark themes

- packages/common/utils/src/Masker.ts
누구나 이해할 수 있도록 회사 내부에서 사용하는 줄임말 대신
정식 명칭을 사용하도록 수정합니다
===
줄임말인 `개보위` 를 `개인정보보호위원회` 로 변경합니다.
> docs: use full name instead of abbreviation

- packages/common/utils/src/object/index.ts
ISSUE CLOSED: #6
불필요한 index 페이지가 @toss/utils에 있어서 @tossdocs-ignore 했습니다.
> docs: ignore tossdocs on unnecessary index.ts on @toss/utils

- packages/common/utils/src/device/isMobileWeb.ts
ISSUES CLOSED: #2
@toss/utils isMobileWeb의 설명이 쓰여 있지 않아서 업데이트했습니다
> docs: update document for @toss/utils isMobileWeb

- packages/common/ky/README.md
ISSUE CLOSED: #4
@toss/ky의 document를 다른 사이드바 메뉴와 통일성을 갖게 합니다.
> docs: update document for consistency of @toss/ky

- packages/common/validators/src/index.ts
ISSUE CLOSED: #8
불필요한 index 페이지가 @toss/validators에 있어서 @tossdocs-ignore 했습니다.
> docs: ignore tossdocs on unnecessary index.ts on @toss/validators

- README-ko_kr.md
- README.md
- packages/react/use-query-param/src/hooks/useQueryParams.ts
===
- 변경사항
- 변경 전:`packages/utils`
- 변경 후:`packages/common/utils`
- 변경사유
- 실제 경로에 맞추어 업데이트해서 링크 깨짐을 해결합니다.
- 영향범위
- `README.md` 문서 (한/영)
- `useQueryParams.ts` 주석
> docs: fix broken links

- packages/react/react/src/hooks/useBodyClass.ts
===
Dan Abramov가 작성한 [uselayouteffect-ssr.md](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85)에 따르면
`useLayoutEffect` 와 `useEffect`는 서버에서는 실행되지 않는다고 합니다.
따라서 `useIsomorphicLayoutEffect` 안에 작성된 로직은 항상 클라이언트에서 실행되는 것이 보장되므로 서버인지 체크하는 로직은 불필요하다고 판단됩니다.
> refactor: remove unnecessary logic in useBodyClass

- docs/docusaurus.config.js
- docs/styles.css
Apply "Toss Product Sans" to make the website's look and feel better.
> chore: Apply Toss Product Sans to our website

- packages/common/utils/src/array/isNonEmptyArray.ts
- #45 
example 의 결과값이 잘못되어있는것을 고칩니다.
> chore(utils): fix example result in isNonEmptyArray

- packages/common/storage/src/typed/storages/TypedStorage.en.md
- packages/common/storage/src/typed/storages/TypedStorage.ko.md
Update our storage docs for a more relevant example.
> docs(storage): Update our docs

- packages/react/error-boundary/src/ErrorBoundary.tsx
There are 404 urls. so I deleted them
https://github.com/tosspayments/frontend/pull/955#pullrequestreview-568141641
https://github.com/tosspayments/frontend/pull/964#pullrequestreview-568847692
> docs(error-boundary): remove 404 urls

- packages/react/react/src/hooks/useCheckList.spec.ts
While observing the too useful useCheckList hook, I found that the test code for the two functions(updateItem, getCheckedIds) was missing. I wrote a test code for it.
2. I have written documents and tests, if needed.  yes😎
> test(react): write useCheckList missing test code

- packages/react/react/src/hooks/useThrottle.ts
This PR is a part of https://github.com/toss/slash/pull/95#discussion_r1007180566
> fix(react): preserves a reference of `options` parameter of `useThrottle`

- packages/react/react/src/components/SwitchCase/SwitchCase.tsx
Add missing commas to SwitchCase examples
> chore(react): add missing comma to example

- packages/common/ky/README.ko.md
- packages/common/ky/README.md
- packages/common/recoil/src/utils/clearRecoilCache.en.md
- packages/common/recoil/src/utils/clearRecoilCache.ko.md
- packages/common/recoil/src/utils/clearRecoilCache.ts
- packages/react/a11y/src/ScreenReaderOnly/index.en.md
- packages/react/async-stylesheet/src/index.en.md
Added some English translation to our docs.
> docs: Add some English translations to our docs

- docs/styles.css
- packages/react/emotion-utils/src/Stack.en.md
- packages/react/emotion-utils/src/Stack.ko.md
- packages/react/emotion-utils/src/box-spacing_margin.en.md
- packages/react/emotion-utils/src/box-spacing_margin.ko.md
- packages/react/emotion-utils/src/box-spacing_padding.en.md
- packages/react/emotion-utils/src/box-spacing_padding.ko.md
- packages/react/emotion-utils/src/gutter.en.md
- packages/react/emotion-utils/src/gutter.ko.md
Added some Sandpack docs for emotion-utils.
> docs(emotion-utils): Add Sandpack docs for emotion-utils

- .circleci/config.yml
Correct wrong spelling in .circleci/config.yml
> docs(.circleci/config.yml): correct spelling

- packages/common/ky/package.json
Add a specific field to support using ky in react-native.
> feat(ky): support react-native

- packages/common/utils/src/object/omit.ts
omit function have two docs because implemented file doesn't have `/** @tossdocs-ignore */` comment
> docs(utils): add /** @tossdocs-ignore */ in omit function

- .circleci/config.yml
This enables tests to be run in forked pull requests.
> chore: Remove `npm-public` context from `test`

- packages/common/storage/src/typed/storages/TypedStorage.spec.ts
- added a test code because there was no verification of the `clear` method.
- translate to english
> feat(storage): test code for clear method

- docs/pages/index.md
Add Jumbotron
- Desktop
- Mobile
> feat: add Jumbtron in index page

- packages/react/react/src/components/ClickArea/ClickArea.tsx
- packages/react/react/src/components/ClickArea/index.test.tsx
> fix(react): `onClick` event issue @ `ClickArea`

- packages/react/error-boundary/src/ErrorBoundaryGroup.ko.md
- packages/react/error-boundary/src/ErrorBoundaryGroup.tsx
- md file for [slash.page](https://slash.page) (Korean first and English later if Korean is OK for reviewer)
- jsdocs to improve easier DX
> docs(error-boundary): add description of ErrorBoundaryGroup

- packages/react/error-boundary/src/ErrorBoundary.ko.md
> docs(error-boundary): remove unnecessary title

- packages/common/crypto/src/pkcs1/encrypt.en.md
- packages/common/crypto/src/pkcs1/encrypt.ko.md
- packages/common/crypto/src/utils.en.md
- packages/common/crypto/src/utils.ko.md
> docs(crypto): fix typo

- packages/react/react/src/components/OpenGraph/OpenGraph.tsx
> fix(react): remove useless fragment tag

- packages/react/async-boundary/package.json
Remove unnecessary dependency(@types/react-dom) to devDependencies
> fix(async-boundary): remove @types/react-dom of dependencies to devDependencies

- packages/react/emotion-utils/src/coerceCssPixelValue.en.md
- packages/react/emotion-utils/src/coerceCssPixelValue.spec.tsx
- packages/react/react/src/components/OpenGraph/OpenGraph.tsx
- To ensure the stability of the `coerceCssPixelValue` function, a test code was written.
- wrote English document for `coerceCssPixelValue` function
2. I have written documents and tests, if needed. yes!
> test(@toss/emotion-utils): write test code for coerceCssPixelValue

- packages/react/react/src/hooks/useForceUpdate.ts
fix useForceUpdate jsdoc
- added examples used in useCheckList
- useReduce -> useReducer fix type
> docs(react): fix useForceUpdate jsdoc

- packages/react/react/src/hooks/useCheckList.ts
> docs(react): fix useCheckList jsdoc

- packages/react/react/src/hooks/useTimeout.ts
You have deleted meaningless comments that are unlikely to be used again.
> refactor(@toss/react): removed unused comment.

- packages/react/react/src/hooks/useForceUpdate.spec.tsx
A test code has been created to validate the behavior of the useForceUpdate
> test(@toss/react): wrote test code for useForceUpdate

- packages/common/storage/src/storage.ts
- packages/react/react/src/hooks/useStorageState.spec.ts
added `clear method` to the Storage implementation in @toss/storage.
it removes all data stored in the Storage
> feat(@toss/storage): add clear method

- packages/react/react/src/hooks/useVisibilityEvent.en.md
- packages/react/react/src/hooks/useVisibilityEvent.ko.md
I have added an example for the missing useVisibilityEvent.
> docs(react): Add example for useVisibilityEvent.

- packages/common/utils/src/clipboard.ts
- packages/common/utils/src/object/omit.ts
Change import path `from "."` to `from "./<package>"`
> chore(@toss/utils): fix circular dependency warning

- packages/common/utils/src/device/isMobileWeb.ts
Refactor isMobile.ts using getOSByUserAgent.ts
pros
- Unify the level of abstraction inside a function.
- Create dependencies between functions that are related to each other
When supporting different mobile OS, not using getOSByUserAgent.ts increases duplication and complexity.
```js
// getOsByUserAgent.ts
export function getOSByUserAgent() {
// ...
// ...
const isBlackBerry = window.navigator.userAgent.match(/BlackBerry/i) !== null; <- duplication
if (isBlackBerry) {
return 'blackberry';
}
return 'web';
}
// isMobileWeb.ts
import { isServer } from './isServer';
export function isMobileWeb() {
if (isServer()) {
return false;
}
if (
navigator.userAgent.match(/ipad|iphone/i) !== null ||
navigator.userAgent.match(/Android/i) !== null ||
navigator.userAgent.match(/BlackBerry/i) !== null.  <- …
```
> fix(@toss/utils): refactor isMobile.ts using getOSByUserAgent.ts

- packages/react/use-loading/src/useLoading.spec.ts
Update test description ko to en. ref: https://github.com/toss/slash/pull/267#issuecomment-1603016177
> chore(@toss/use-loading): Update test description ko to en

- packages/react/react/src/hooks/useIsMounted.spec.tsx
I wrote some test code that is very simple, but needs to return true when the useIsMounted Hook is mounted. 🙏
> test(@toss/react): Add useIsMounted Test Code

- packages/common/utils/src/Masker.ts
- packages/common/utils/src/batchRequestsOf.ts
- packages/common/utils/src/clipboard.ts
- packages/common/utils/src/copyToClipboard.spec.ts
- packages/common/utils/src/copyToClipboard.ts
- packages/common/utils/src/index.ts
- packages/common/utils/src/loadScript.ts
> fix(utils): Merge @tossteam/utils

- packages/react/error-boundary/src/ErrorBoundary.tsx
> fix(error-boundary): Merge @tossteam/error-boundary

- packages/react/redirect/src/base/boundary/RedirectionBoundary.tsx
- packages/react/redirect/src/base/boundary/index.test.tsx
- packages/react/redirect/src/base/model/Redirection.ts
This PR merges the internal changes into OSS.
> merge(redirection): merge internal changes

- packages/common/utils/src/identity.spec.ts
I wrote a simple test code for the `identity` function in `toss/utils`.
> test(@toss/utils): Add identity function Test Code

- packages/react/react/src/hooks/useCheckList.ko.md
> docs(@toss/react): fix useCheckList.ko 존댓말로 변경

- packages/common/utils/src/reverseKeyValue.ko.md
> docs(@toss/utils): add reverseKeyValue dot

- packages/react/use-funnel/README.ko.md
- packages/react/use-funnel/README.md
> docs(use-funnel): fix typo in example

- tsconfig.json
Add string spacing in tsconfig.json
> fix: Add string spacing

- packages/react/react/src/hooks/useTimeout.en.md
- packages/react/react/src/hooks/useTimeout.ko.md
- packages/react/react/src/hooks/useTimeout.ts
I added a dependency array to `useTimeout` and renamed it from `id` to `timeoutId` to give it a clearer meaning.
I also modified the example code in the `useTimeout` documentation.
After modifying the code, all tests passed! 🙏
https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#return_value
> fix(@toss/react): Add dependency array to useTimeout and rename timeoutId

- packages/react/react/src/hooks/useCombinedRefs.en.md
- packages/react/react/src/hooks/useCombinedRefs.ko.md
- packages/react/react/src/hooks/useCombinedRefs.spec.tsx
- packages/react/react/src/hooks/useRefEffect.ts
I improved the `useCombinedRefs` documentation and replaced the `noop` used inside `useRefEffect` with the `noop` from `@toss/utils`. 🙏
> fix(react): useCombinedRefs docs

- packages/common/utils/README.ko.md
- packages/common/utils/README.md
- packages/react/use-query-param/README.ko.md
- packages/react/use-query-param/README.md
add various install guides
- npm
- pnpm
> docs: add various install guides

- packages/react/react/src/components/SwitchCase/index.test.tsx
- [`fd5ff7a`](https://github.com/SEOKKAMONI/slash/commit/fd5ff7ab848055dac65d347671af42120f1d8eaf) rewrite SwitchCase test code in english
> test(@toss/react): rewrite SwitchCase test code in english

- configs/rollup/src/index.js
Due to the nature of "Open source", I think it should provide good readability to people who read code for the first time. So I improved readability through clear allocation of variables and step-by-step processing.
> chore(@toss/rollup-config): Improve readbility for the rollup settings

- packages/react/error-boundary/src/ErrorBoundaryGroup.en.md
- packages/react/error-boundary/src/ErrorBoundaryGroup.ko.md
I updated documents links of ErrorBoundaryGroup
> docs(error-boundary): update links for ErrorBoundaryGroup

- packages/common/assert/src/assert.test.ts
1. I changed the sentence in the test code to English.
2. Reinforced the test code
[ Before ]
[ After ]
> test(@toss/assert) : Reinforced the test code

- packages/react/react/src/components/ClickArea/index.test.tsx
- I use `getByRole` instead of `getAllByRole` to  reduce complexity and improves the readability of the test code.
- Updated the click event tests to use `userEvent.click`
- Introduced a constant `ENABLED_CLASS_NAME` to replace hardcoded class name strings
- general code clean up
thanks!
> test(@toss/react): Refactor `ClickArea` Component Tests

- packages/react/react/src/components/HiddenHeading/index.spec.tsx
add test cases to HiddenHeadning & change to english from korean
> test(@toss/react): add test cases to HiddenHeadning & change to english from korean

- packages/common/utils/src/uniqWith.spec.ts
I've added tests for [uniqWith](https://github.com/toss/slash/blob/main/packages/common/utils/src/uniqWith.ts) function.
thanks!
> test(@toss/utils): add test code for `uniqWith` function

- packages/common/date/src/date.spec.ts
Before I modified the code, I referred to [#267 (comment)](https://github.com/toss/slash/pull/267#discussion_r1248051773).
[ What did i do]
1. I changed some Korean words to English words. I referred to [#36 (comment)](https://github.com/toss/slash/pull/36#issuecomment-1275904567)
2. Corrected typos.
3. Test code has been changed to be semantically readable.
4. Add new test code(roundUpHoursInDays, isEqualOrBefore, isEqualOrAfter)
> test(@toss/date): Add test code and change grammar semantically

- packages/react/react/src/components/Separated/index.spec.tsx
i add test code to Separated component
> test(@toss/react): add test of `Separated`

- packages/common/utils/src/Masker.spec.ts
1. Change korean to english in `masker.spec.ts`
> test(@toss/utils): change korean to english in masker

- packages/react/emotion-utils/src/gutter.test.tsx
> test(@toss/emotion-utils): improve gutter test coverage

- packages/react/emotion-utils/src/spacing.spec.tsx
> test(@toss/emotion-utils): add test code to spacing

- packages/react/use-funnel/src/Funnel.tsx
- packages/react/use-overlay/src/tests/close-reference.spec.tsx
- packages/react/use-overlay/src/tests/options.spec.tsx
- Change korean to english in close-reference.spec.tsx
- Change korean to english in options.spec.tsx
> test(use-overlay): Change korean to english in test code

- packages/common/utils/src/chunk.spec.ts
1. Change korean to english in `chunk.spec.ts`
> test(@toss/utils) : Change korean to english in chunk

- packages/common/utils/src/batchRequestsOf.spec.ts
1. Change korean to english in `batchRequestsOf.spec.ts`
> test(@toss/utils): change korean to english in batchRequestsOf

- packages/react/react/src/hooks/useOutsideClickEffect.spec.tsx
1. Improve test accuracy
-i've change`expect(onEffect).toHaveBeenCalled()` to `expect(onEffect).toHaveBeenCalledTimes(n)`
> test(@toss/react): update test of `useOutsideClickEffect`

- packages/common/crypto/src/pkcs1/encrypt.ts
Change Normal Comment with Tsdocs.
<br>
Before we need copy link and open browser to paste it, after we don't need to paste link but we can click by ctrl + click and open new tab.
I attached video.
> chore(@crypto): Improve Comment Readability with tsdocs

- packages/common/utils/src/noop.spec.ts
1. The missing "noop" function has been added to the test.
2. Switch the "asyncNoop" test from Korean to English.
[ AS-IS ]
[ TO-BE ]
> test(@toss/utils): Improve test for noop

- packages/common/utils/src/index.ts
- packages/common/utils/src/isNil.en.md
- packages/common/utils/src/isNil.ko.md
- packages/common/utils/src/isNil.spec.ts
- packages/common/utils/src/isNil.ts
> feat(@toss/utils): Add `isNil` util function

- packages/react/lottie/src/LottieRef.ts
- packages/react/lottie/src/SuspendedLottie.tsx
Remove empty pages from lottie directory by adding `@tossdocs-ignore`
|LottieRef|SuspendedLottie|
|:-:|:-:|
|![image](https://github.com/toss/slash/assets/58380158/9ceb9e57-5d0c-4bf2-9dd8-de045eae7198)|![image](https://github.com/toss/slash/assets/58380158/c66097ec-23e0-4137-a146-3e2564abeffa)|
> chore(@toss/react): remove empty pages from lottie directory by adding `@tossdocs-ignore`

- packages/react/impression-area/src/ImpressionArea.tsx
- packages/react/impression-area/src/useImpressionRef.tsx
I worked on refactoring `ImpressionArea` and `useImpressionRef`. All tests worked fine. 
I left a description of the task as a comment..!! 
I'd appreciate it if you could review it. 🙏
> refac(impression-area): Improved ImpressionArea and useImpressionRef

- packages/common/utils/src/setFocusTimeout.spec.ts
- packages/common/utils/src/setFocusTimeout.ts
Korean comments about setFocusTimeout have been replaced with English.
I wrote a test case for setFocusTimeout.
> test(@toss/utils): Add new test for setFocusTimeout

- packages/common/utils/src/scrollRestoration.spec.ts
add `scrollRestoration` test code.
> test(@toss/utils): Add new test for scrollRestoration

- packages/common/utils/src/queryString.ts
**Corrected** typos and made sentences **smooth** in jsdoc in `createSearchParamString`. (7382bb094be56dceba7319c13c53ff15b764a806)
> docs(@toss/utils): fix tsdoc in createSearchParamString

- packages/common/utils/src/array/arrayIncludes.spec.ts
Fixes https://github.com/toss/slash/issues/416 
@ghdtjgus76 위 이슈에서 공유해주신 해결법 두 가지는 아래 스샷처럼 eslint에러가 나서 assertion 방식으로 수정했습니다!! 
❌
❌
✅
- [✅] I read and included theses actions below
> test(@toss/utils): Change test code to string assertion

- packages/common/utils/src/getScrollPercent.spec.ts
add getScrollPercent test code.
> test(@toss/utils): Add new test for getScrollPercent

- packages/react/react/src/hooks/useCheckList.spec.ts
We improved coverage of the useCheckList Hook by writing a test case to ensure that the conditional logic within the updateItem and updateAll functions works as expected.
[AS-IS]
[TO-BE]
> test(@toss/react): improve useCheckList test coverage

- packages/common/utils/src/getScrollDiffFromBottom.spec.ts
add getScrollDiffFromBottom test code.
> test(@toss/utils): Add new test for getScrollDiffFromBottom

- packages/common/utils/src/difference.spec.ts
Changed the Korean descriptions in the difference test file to English.
> test(@toss/utils): rewrite difference, differenceWith test code in english

- packages/common/validators/src/validators/is-age.spec.ts
1. translate into english from isAge test
> test(@toss/validators): Improve test for isAge

- packages/common/validators/src/validators/is-사업자번호.en.md
- packages/common/validators/src/validators/is-사업자번호.ko.md
- packages/common/validators/src/validators/is-사업자번호.spec.ts
1. Removed an invalid web link.
2. Changed the test code to English
> docs(@toss/validators), test(@toss/validators) : remove web link, translate into english for isBusinessRegNo

- packages/common/utils/src/device/getOSByUserAgent.spec.ts
1. add getOSByUserAgent's test code.
[ AS-IS ]
[ TO-BE ]
> test(@toss/utils): Add new test for getOSByUserAgent

- packages/common/utils/src/device/isMobileWeb.spec.ts
1. Add isMobileWeb's test code.
[ AS-IS ]
[ TO-BE ]
> test(@toss/utils): Add new test for isMobileWeb

- packages/common/utils/src/device/isMacOS.spec.ts
1. Add isMacOS's test code. I referred to [this code](https://github.com/toss/slash/pull/407/files#diff-ab89db514dc672c9b3112a74db6c4565ad94d623488a107e4cd02dc8fa08711c).
[ AS-IS ]
[ TO-BE ]
> test(@toss/utils): Add new test for isMacOS

- packages/react/use-funnel/README.ko.md
- packages/react/use-funnel/README.md
> fix(use-funnel): add canonical meta and add migration guide link
