packages/common/utility-types/package.json, packages/react/impression-area/package.json
Fixes https://github.com/toss/slash/issues/12
===
An incorrect filepath is specified in `@toss/impression-area`'s package.json `module` field. We fix this issue.
Also, `@toss/utility-types` is a typescript-only package. There is no need for ESM files, so we remove other fields in `publishConfig`.
`@toss/impression-area` 패키지의 `module` 필드가 올바른 확장자를 쓰고 있지 않아서 수정합니다.
`@toss/utility-types` 패키지는 TypeScript 전용이므로 ESM 관련 대응을 할 필요가 없습니다. `publishConfig` 에서 관련 설정을 제거합니다.
=> fix: Fix incorrect `module` field in package.json

configs/rollup/src/index.js, packages/react/react/src/hooks/useBodyClass.ts
- 사용하지 않는 module을 import하는 코드를 삭제합니다.
- #12  관련하여 고정된 `.mjs` 대신 conditional exports map 기반으로 ESM 번들링 파일(specially extension)을 생성하기 위해 rollup config를 수정합니다.
===
- `packages/react/react/src/hooks/useBodyClass.ts`에서 사용되지 않는 module을 import하는 코드를 삭제하였습니다.
- rollup config 내 ESM 번들링을 위한 output 파일 경로의 확장자를 .mjs로 명시하는 것 대신에 exports.import 파일 확장자로 사용하게끔 수정하였습니다.
=> refactor: buildESM at rollup config

packages/common/utils/src/generateID.spec.ts
I wrote test code for generateID which belong to @toss/utils To ensure stability, I have written a test code
`nextUniqueId` which is local variable in generateID should be initialized to 0 for every test case
so I used jest.resetModules 
resetModules help our individual test code run independently from other test cases
2. I have written documents and tests, if needed. => I made test case !
=> test(utils): Add test code for generateID

packages/common/utils/src/format.ts
fix wrong example of maskName function
=> chore(utils): fix wrong example of maskName function

packages/react/emotion-utils/src/coerceCssPixelValue.ts, packages/react/emotion-utils/src/mediaQuery.ts, packages/react/emotion-utils/src/spacing.tsx
in emotion-utils 
they have type CSSPixelValue which is union type string and number
`type CSSPixelValue = string | number;`
Some file didn't use the CSSPixelValue in a specific part.
I thought this would undermine the unity of the project, so I improved it to use the defined type(CSSPixelValue).
=> refactor(emotion-utils): union type reused by predefined type 

packages/common/date/src/date.spec.ts
in date.spec.ts
```typescript
const date = parseYYYYMMDD('2020-04-23');
expect(date.getFullYear()).toEqual(2020);
expect(date.getMonth()).toEqual(3);
expect(date.getDate()).toEqual(23);
```
date cannot be null because parseYYYYMMDD return only Date type anytime unless throw error
Therefore, if the value is returned, it is absolutely a Date type so question mark is useless!
=> fix(date): remove useless null check question mark in spec file

packages/common/hangul/src/disassembleHangul.en.md, packages/common/hangul/src/disassembleHangul.ko.md
Thank you for making this awesome library public!
Reading @toss/hangul docs, I just came across a small typo.
Please review my suggestion for renaming the function.
`disassembleHangulToGroups()` ➜ `disassembleHangul()`
2. I have written documents and tests if needed.
=> docs(hangul): fix typos in disassembleHangul

configs/rollup/src/index.js
```javascript
// configs/rollup/src/index.js
exports.generateRollupConfig = function generateRollupConfig({ packageDir, entrypoints: _entrypoints }) { ... }
```
I deleted the unused `_entrypoints` from the `generateRollupConfig` function.  
Check please :D
=> refactor(rollup): remove unused argument

packages/react/error-boundary/src/ErrorBoundary.en.md, packages/react/error-boundary/src/ErrorBoundary.ko.md, packages/react/error-boundary/src/ErrorBoundary.tsx, packages/react/error-boundary/src/useErrorBoundary.en.md, packages/react/error-boundary/src/useErrorBoundary.ko.md, packages/react/error-boundary/src/useErrorBoundary.ts
I translated the package to make it easier for others to use @toss/error-boundary, which helps them manage errors declaratively.
=> docs: migrates jsdoc to i18n for @toss/error-boundary

.pnp.cjs, package.json, yarn.lock
There are type errors that cannot resolve `jest` utils in all test files.
`tsconfig.json` in the root doesn't exclude any test files. But, in the package, it's excluded by extended `tsconfig.build.json`.
So I added `@types/jest` to root to avoid the errors.
=> fix: add `@types/jest` to the root

packages/common/utils/src/Numbers.spec.ts, packages/common/utils/src/Numbers_decommaize.en.md, packages/common/utils/src/Numbers_decommaize.ko.md
- Docs example for decommaizeNumber was given as an example for commaizeNumber. 
- [fix: @toss/utils decommaizeNumber docs](https://github.com/toss/slash/commit/1e5d1f716d5e1943dcf6f900bc80a2d9775cc1bc)
- There are no test codes created for decommaizeNumber, so I wrote some.
-   [feat: @toss/utils write decommaizeNumber test code](https://github.com/toss/slash/commit/e7c04c1abb1b8599d96dd99349e123112394fb12)
=> fix(utils): fix incorrect example in docs & add test code

packages/common/utils/src/partition.ts, packages/common/utils/src/range.ts, packages/common/utils/src/retryRequestsOf.ts, packages/common/utils/src/reverseKeyValue.ts, packages/common/utils/src/safeScrollTo.ts
While reading the slash docs, I found that some function have duplicated docs. I added comments `/** @tossdocs-ignore */` because it creates jsdoc automatically.
I think it related with https://github.com/toss/slash/pull/113
=> chore(utils): remove duplicated docs

packages/react/emotion-utils/src/utils/position.test.tsx, packages/react/emotion-utils/src/utils/position.ts
- Add position's function method(absolute, fixed, sticky)
```
position.absolute({ top: 0, left: 0 });
position.absolute(0, 0, 0, 0);
```
- Add example code as comments
- Add test case
- Duplicate code exists. I tried several ways but failed. Please let me know if there is a better way
- cc https://github.com/toss/slash/issues/100
=> feat(emotion-utils): Add position's function method(absolute, fixed, sticky)

docs/pages/index.md
The @toss/react page appears as not found.
The link address is invalid, so I fixed it with the correct link.
=> docs: Fix incorrect address in @toss/react

.circleci/config.yml
There is a legacy git setup step in our CI config, making forked pull requests not built. Removed this step to make forked PRs to be checked correctly.
=> ci: Remove unnecessary git setup step

packages/react/lottie/src/Lottie.tsx
- `startAnimation` is called in `useEffect`, but it depends on `onPlay` prop.
- So if the reference of `onPlay` was changed, `startAnimation` would be changed too and then be called again.
- Users can see the animation from the beginning on every render.
- So I wrapped all event handler props by `usePreservedCallback`.
=> fix(lottie): Preserves references of event handler props for Lottie

packages/react/react/src/hooks/useInterval.ts
I change InvervalOptions to IntervalOptions which is typo I think!
=> docs(react): IntervalOptions typo

packages/common/utils/src/object/index.ts, packages/common/utils/src/object/omit.en.md, packages/common/utils/src/object/omit.ko.md, packages/common/utils/src/object/omit.ts
added utility function `omit`;
constructs new object by removing the key-value pairs corresponding to the given keys from the object. (omitted type is inferred)
=> feat(utils): add omit

docs/i18n/ko/docusaurus-plugin-content-pages/index.md
updated broken kr docs link
from [**@toss/react**](https://slash.page/libraries/react/react/src/components/ClickArea/ClickArea.tsx.tossdocs)
to [**@toss/react**](https://slash.page/ko/libraries/react/react/src/components/clickarea/clickarea.i18n)
=> docs: fix broken kr react link

configs/rollup/src/index.js
Our rollup config does not have `preserveModulesRoot`, making the directory structure of output folder `esm` wrong. 
This pull request fixes this behavior with `preserveModulesRoot`.
=> fix(rollup-config): Add `preserveModulesRoot` to our rollup config

packages/react/use-overlay/src/OverlayProvider.tsx, packages/react/use-overlay/src/useOverlay.tsx
1. remove unused props `containerId` it is not used
2. change key of array 
The value id is generated uniquely every time overlay is used, so I think it can be used as the key of the array. Is there a any reason for using new Date() as a key?
=> fix(use-overlay): remove unused props

packages/react/use-overlay/src/tests/exit.spec.tsx, packages/react/use-overlay/src/useOverlay.en.md, packages/react/use-overlay/src/useOverlay.ko.md, packages/react/use-overlay/src/useOverlay.tsx
related with #146
- Abstracts and returns the function so that developers using `useOverlay` can unmount the overlay from the outside.
- wrote proper test code for verify this function
=> feat(use-overlay): add exit function 

packages/react/emotion-utils/src/flex.tsx
Correct naming
Wrong naming found during [this PR](https://github.com/toss/slash/pull/149)
current FlexReturnType is not return type. so I edited it
FlexReturnType => BaseFlexType
=> refactor(emotion-utils): correct FlexReturnType naming to BaseFlexType

.eslintignore
add dist esm in .eslintignore to ignore eslint after all packages build
I don't want to see error in dist esm, and don't want to let them can be formatted on save.
=> chore: add dist, esm to ignore eslint after all packages build

packages/react/react-query/test-d/index.test-d.ts
[In this url](https://slash.page/libraries/react/react-query/test-d/index.test-d.ts.tossdocs) 
there is a dummy page because of test.d.ts file 
So I add tossdocs ignore comment as convention.
=> docs(react-query): remove react-query dummy docs

packages/common/assert/package.json, packages/common/crypto/package.json, packages/common/date/package.json, packages/common/hangul/package.json, packages/common/sentry/package.json, packages/common/storage/package.json, packages/common/utility-types/package.json, packages/common/utils/package.json, packages/common/validators/package.json, packages/react/a11y/package.json, packages/react/async-boundary/package.json, packages/react/async-stylesheet/package.json, packages/react/emotion-utils/package.json, packages/react/error-boundary/package.json, packages/react/framer-motion/package.json, packages/react/impression-area/package.json, packages/react/lottie/package.json, packages/react/react-query/package.json, packages/react/react/package.json, packages/react/recoil/package.json, packages/react/redirect/package.json, packages/react/scroll-animation/package.json, packages/react/use-funnel/package.json, packages/react/use-loading/package.json, packages/react/use-overlay/package.json, packages/react/use-query-param/package.json
ISSUE CLOSE: #166 
If not using files field, @toss/slash user can see unnecessary files in node_modules like @toss/error-boundary's jest.config.js, jest.setup.ts etc.
I used files filed as ["dist", "esm"], but we don't have to worry about ignoring necessary files like package.json, README, LICENSE that almost be used as filename in @toss/slash. because below filename will be contained in package defaultly.
Certain files are always included, regardless of settings:
- package.json
- README
- LICENSE / LICENCE
- The file in the "main" field
- README & LICENSE can have any case and extension.
package.json have to narrow files to publish package contain only necessary. by using files field, we can narrow package's files. so I added files field in 05e1c07
@toss/ky have other directory structure …
=> refactor(package.json): remove unnecessary files of all packages

packages/react/react-query/src/hooks/useSuspendedQuery.ts, packages/react/react-query/test-d/index.test-d.ts
There was exported type `SuspendedUseQueryResultOnIdle` with generic to type TData. but SuspendedUseQueryResultOnIdle's purpose is for idle status of Promise, so It cannot be filled TData without undefined. so I remove chance to use generic of SuspendedUseQueryResultOnIdle.
=> fix(react-query): remove chance to use generic of type SuspendedUseQueryResultOnIdle

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Correct wrong spelling with auto format
1. Repot -> Report
2. Auto format by VSCode.
=> fix(.github): correct wrong spelling with auto format

packages/common/sentry/package.json, packages/common/sentry/src/testing/index.mts
Fix `@toss/sentry/testing` subpath export.
```ts
import { useFakeSentry } from '@toss/sentry/testing';
```
=> fix(sentry): expose `./testing` subpath export

packages/react/error-boundary/src/ErrorBoundary.tsx
Remove unnecessary comment
When I click link of comment, I can't understand what this comment mean.
If it have meaning, how about clarifying it?
=> fix(error-boundary): remove unnecessary comment

packages/react/error-boundary/src/ErrorBoundaryGroup.spec.tsx, packages/react/error-boundary/src/ErrorBoundaryGroup.tsx
Optimize return of useErrorBoundaryGroup by using useMemo
```tsx
const Comp = () => {
// useErrorBoundaryGroup make new object, whenever Comp is rendered, for return type(group)
const group = useErrorBoundaryGroup 
...
}
```
```tsx
const Comp = () => {
// useErrorBoundaryGroup don't make new object, whenever Comp is rendered, for return type(group) 
const group = useErrorBoundaryGroup 
...
}
```
=> perf(error-boundary): optimize return of useErrorBoundaryGroup

packages/react/react/src/hooks/useCombinedRefs.ts
@HoseungJang, I found you want to prevent that useCombinedRefs accept MutableRefObject in https://github.com/toss/slash/pull/211#discussion_r1097071688. so I understood why useCombinedRefs not accepting MutableRefObject is to prevent ref.current's mutation by readonly field of RefObject, making TypeScript error if trying mutation of ref.current.
But, in example, useCombinedRefs accept MutableRefObject, so I fixed it.
also Thanks to @tooooo1 that make this https://github.com/toss/slash/pull/211
=> docs(react): fix example of useCombinedRefs's js-doc

packages/react/react/src/hooks/useCombinedRefs.ts
```ts
export function useCombinedRefs<T>(...refs: Array<Ref<T> | CallbackRef<T>>): Ref<T> {
return useCallback(
(value: T) => {
for (const ref of refs) {
if (typeof ref === 'function') {
ref(value);
} else if (ref != null) {
(ref as MutableRefObject<T>).current = value;
}
}
},
[refs] // always new reference of refs
);
}
```
Inside of useCombinedRefs, refs arrary will be always new array between re-renders. so useCallback in useCombinedRefs have no [feature of caching function definition between re-renders](https://beta.reactjs.org/reference/react/useCallback) so I spread it to fix it correctly.
and then I added eslint-disable-next-line.
```ts
export function useCombinedRefs<T>(...refs: Array<Ref<T> | CallbackRef<T>>): Ref<T> {
return useCallback(
(value: T) => {
for (const ref of refs) { …
```
=> fix(react): make correct way to use useCallback's dependencyList in useCombinedRefs

packages/common/utils/src/object/pick.spec.ts, packages/common/utils/src/object/pick.ts
Although the object's key value could be a symbol, the array of keys was blocked from entering the symbol.
I think I've limited it in the past because of [this issue](https://github.com/microsoft/TypeScript/issues/24622), but now the keyof command works well for the object to which the symbol belongs.
If there's any other reason why `pick` function blocked the symbol, please tell me!
=> fix(utils): remove the type that deleted the symbol which name is `ObjectKeys`.

docs/i18n/ko/docusaurus-plugin-content-pages/index.md, docs/pages/index.md
- The part where the banner looks different on the English page and the Korean page is unified to match the English page.
- The reason why I changed it to English page is because the commit log of the banner addition code is more recent. (I think the English page is prettier aesthetically 👀)
=> docs(i18n):  Edit banner style

packages/react/react/src/hooks/useStorageState.spec.ts, packages/react/react/src/hooks/useStorageState.ts
````typescript
// const state: 0       Before this PR
// const state: number  After this PR
const [state, setState, refresh] = useStorageState('number', {
defaultValue: 0
})
````
This pull request updates the type definition of defaultValue in codebase to be inferred as a primitive type instead of a literal value. 
To achieve this, I updated the `useStorageState` function's generic type parameter to extends `Serializable` instead of using defaultValue as a `Serializable<T>`.
Pull Request about https://github.com/toss/slash/issues/220
=> fix(react): infer defaultValue as primitive type

packages/react/emotion-utils/src/utils/position.test.tsx
`import '@testing-library/jest-dom';` statement is declared in jest.setup.ts so in test file it is useless! 
so I removed it
=> test(emotion-utils): remove useless import statement

packages/common/storage/package.json, packages/common/storage/typed.d.ts, packages/common/storage/typed.ts
I delete uselsess typed.ts file in root path in @toss/storage [66f44a2](https://github.com/toss/slash/commit/66f44a217a638b4bc3205239a5fdcb6b2048eb07)
Add typed.d.ts file for subpath module in @toss/storage (/typed) [16d3c64](https://github.com/toss/slash/commit/16d3c647febdb7739016a97bece0a92bc98e509d)
relates to #243 
Thanks to providing simple solution @HoseungJang (https://github.com/toss/slash/pull/247#issuecomment-1575288949)
In PR #247, I updated rollup.config.js by using @toss/rollup-config.
I think in this package too, it is simple way for building files by using @toss/rollup-config
If you agree about update rollup.config.js, can i update that file in this PR? or new branch and create PR.
1. I have read the [Contributing …
=> fix(@toss/storage): Add typed.d.ts file for subpath module

packages/common/utils/src/Numbers_formatToKRW.en.md, packages/common/utils/src/Numbers_formatToKRW.ko.md
I think there might be incorrect content remaining while copying from formatToKoreanNumber document
- fix typo in formatToKRW docs title (formatToKoreanNumber -> formatToKRW)
- update desccription
=> fix(utils): fix typo

packages/common/date/src/docs/getDateDistanceText.en.md, packages/common/utils/src/array/NonEmptyArray.en.md, packages/common/utils/src/array/arrayIncludes.en.md, packages/common/utils/src/array/last.en.md, packages/common/utils/src/object/object-entries.en.md, packages/common/utils/src/object/object-keys.en.md, packages/common/utils/src/object/object-values.en.md, packages/react/impression-area/src/ImpressionArea.en.md, packages/react/impression-area/src/useImpressionRef.en.md
Update the links linked to Korean documents in English docs correctly.
=> docs(i18n): fix link for en docs to ko docs

packages/react/error-boundary/src/ErrorBoundaryGroup.tsx, packages/react/error-boundary/src/index.ts, packages/react/error-boundary/src/withErrorBoundaryGroup.en.md, packages/react/error-boundary/src/withErrorBoundaryGroup.ko.md, packages/react/error-boundary/src/withErrorBoundaryGroup.tsx
I split `withErrorBoundaryGroup` HOC to file like as [withAsyncBoundary](https://slash.page/libraries/react/async-boundary/src/withAsyncBoundary.i18n)
=> docs(@toss/error-boundary): split `withErrorBoundaryGroup` HOC to file with docs

docs/docusaurus.config.js
I add color scheme config to docusaurus.config.js 
Using user system preferences, instead of the hardcoded ([referece](https://docusaurus.io/docs/api/themes/configuration#respectPrefersColorScheme))
https://github.com/toss/slash/assets/57122180/4322cf63-e738-4d7d-8dd3-0db3f1839fa5
=> docs(docs): add colorMode to config file

packages/common/hangul/README.ko.md
Replace the English version of the function list url into Korean version in Korea Docs page.
=> docs(@toss/hangul): replace url of function list eng to kor

packages/react/react/src/hooks/useTimeoutQueue.spec.ts
Change wrong variable names in `@toss/react/useTimeoutQueue` test code.
Because setTimeout returns timeout id, not interval id.
=> chore(@toss/react):  change wrong variable names in `useTimeoutQueue` test code

packages/common/hangul/src/chosungIncludes.ts, packages/common/hangul/src/disassemble.ts, packages/common/hangul/src/hangulIncludes.ts
Current `@toss/hangul` docs have duplicated pages. So add `/** @tossdocs-ignore */` to fix this.
=> fix(@toss/hangul): remove duplicated docs

packages/react/emotion-utils/package.json, packages/react/framer-motion/package.json, packages/react/react-query/package.json, yarn.lock
- react/framer-motion
- react/emotion-utils
- react/react-query
> It means the same thing.
`"react": ">=16.8.0 || ^17.0.0 || ^18"`   === `"react": ">=16.8.0"`  
- [SemVer check](https://semver.npmjs.com/#syntax-examples)    
-  `"react": ">=16.8.0"` ?
-  `"react": "^16.8.0 || ^17.0.0 || ^18"` ?
Considering the presence of the `||` symbols after `>=16.8.0`, it seems that the intended version was `"^16.8.0 || ^17.0.0 || ^18"`. I have modified the semver to `"react": "^16.8.0 || ^17.0.0 || ^18"`.
If the intention was to specify `>=16.8.0`, I will modify it to `"react": ">=16.8.0"`.
<br>
>When using `>=` in conjunction with `||`, it is typically used as follows: [link](https://github.com/nodejs/node-gyp/blob/main/package.json)
```json
"engines": {
"node": "^14.17.0 || ^16.13.0 || >=18.0.0"
}, …
```
=> fix: modify ambiguous SemVer

packages/common/hangul/README.ko.md, packages/common/hangul/README.md
Replace the wrong disassemble function list url  in Eng, Kor Docs page.
=> docs(@toss/hangul): fixed wrong url of function list (about disassemble)

packages/common/utils/src/batchRequestsOf.ts
In slash docs, there is [unneeded page](https://slash.page/ko/libraries/common/utils/src/batchRequestsOf.ts.tossdocs) because of `batchRequestsOf.ts`
It seems that `@tossdocs-ignore` was accidentally deleted while importing the `noop` in #302, then I add it again like any other `.ts` files.
=> docs(@toss/utils): add @tossdocs-ignore to batchRequestsOf

packages/common/validators/src/validators/is-rrn.ts
In slash docs, there is [unneeded page](https://slash.page/ko/libraries/common/validators/src/validators/is-rrn.ts.tossdocs) because of `is-rrn.ts`
Looks like `@tossdocs-ignore` was deleted in #312, so I added it back like any other `.ts` file.
=> docs(@toss/utils): add `@tossdocs-ignore` to `is-rrn.ts`

packages/react/use-overlay/package.json
Moved incorrectly placed `"@types/react"` from dependencies to devDependencies
=> fix(use-overlay): move incorrectly placed package from dependencies to devDependencies

packages/common/utils/src/object/object-keys.ts
It works differently
I got this image error
The two TypeScript type declarations perform fundamentally similar roles, but they result in different types. Here are the differences:
```tsx
export declare type ObjectKeys<T extends Record<PropertyKey, unknown>> = `${Exclude<keyof T, symbol>}`;
```
This declaration converts all property keys of type T into string types. It forces the property keys into string types using Template Literal Types, which is a feature introduced in TypeScript 4.1. Consequently, this type becomes a union of string literals.
```tsx
export declare type ObjectKeys<T extends Record<PropertyKey, unknown>> = Exclude<keyof T, symbol>;
```
This declaration returns all property keys of type T but as keys themselves, not as strings. This type returns a union of all property …
=> fix(@toss/utils): Merge with internal `@tossteam/utils` library

packages/react/error-boundary/src/ErrorBoundaryGroup.spec.tsx, packages/react/react/src/hooks/useCombinedRefs.spec.tsx, packages/react/react/src/hooks/useOutsideClickEffect.spec.tsx, packages/react/use-funnel/src/useFunnel.spec.tsx, packages/react/use-overlay/src/tests/exit.spec.tsx
Starting with userEvent `v14`, it is recommended to call `userEvent.setup()` before rendering the component.
I have refactored the code using userEvent as per the guide.
https://testing-library.com/docs/user-event/intro#writing-tests-with-userevent
=> refac: userEvent Setup Code

packages/react/react/src/utils/buildContext.en.md, packages/react/react/src/utils/buildContext.ko.md
I identified a syntax error in the example code. Upon reviewing the test code, it appears that the example needs to be modified as follows:
```tsx
const [Provider, useContext] = buildContext<{ title: string }>('TestContext', null);
function Inner() {
const context = useContext();
return <h1>{context.title}</h1>;
}
function Page() {
return (
<Provider title="타이틀">
<Inner />
</Provider>
);
}
```
=> docs(@toss/react): fix syntax error in example code

packages/common/utils/src/groupBy.spec.ts
1. Translate groupBy test descriptions from Korean to English for clarity and global team accessibility
2. Enhance groupBy tests with case sensitivity check
I added a new test case because the existing code's test cases were only in Korean, and there was no example case to check if the return value of createKey distinguishes between uppercase and lowercase when it's in English
=> test(@toss/utils): Improve groupBy Function Tests (Translation and Case Sensitivity Enhancement)

packages/common/utils/src/get-set.spec.ts
I've added tests for handling incorrect path formats and empty objects, and improved the descriptions for clarity. 
- Include test to handle paths with consecutive dots in the get function.
- Add test for get function with empty object inputs.
- Implement test for set function to handle incorrect path formats.
- Add test case for set function with empty object inputs.
These tests enhance the robustness of get and set functions by covering additional edge cases
=> test(@toss/utils): Enhance Test Coverage and Clarity for Get and Set Functions

packages/common/utils/src/Numbers_formatBusinessRegistrationNumber.en.md, packages/common/utils/src/Numbers_formatPhoneNumber.en.md
1. Correct typos (hypen -> hyphen) in formatBusinessRegistrationNumber, formatPhoneNumber. You can referred [here](https://dictionary.cambridge.org/dictionary/english-korean/hyphen).
=> docs(@toss/utils) : Correct typos in Numbers

packages/common/utils/src/get-set.spec.ts
1. Improve get-set's uncovered line.
[ Before ]
[ After ] 
=> test(@toss/utils): Improve tests for get-set

packages/common/utils/src/clamp.en.md, packages/common/utils/src/clamp.ko.md
1. I change some comment in docs. Beacuse, `clamp(3, 1)` actually return **1**. But, `chunk.\*.md` returns **3**.
=> docs(@toss/utils): fix typo in clamp docs

packages/react/emotion-utils/src/flex.test.tsx
=> test(@toss/emotion-utils): improve flex test coverage

.gitignore
add coverage to gitignore
Each time a coverage test is conducted, the commitment history contains the contents within the coverage folder, which has an unnecessary impact on the task
=> chore(.gitignore): add coverage to gitignore

packages/common/utils/src/escapeHTML.en.md, packages/common/utils/src/escapeHTML.ko.md, packages/common/utils/src/escapeHTML.spec.ts
1. Match markdown's function parameter name and origin function parameter name.
2. Change korean to english in test code.
[ Proposal ]
The `default` case of the switch statement in "escapeHTML" can never be executed. That's because it's filtered out of "regex."
If default is not executed, it seems that the confusion of the code will only increase.
Can I change default to the 5th case?
You can refer [escapeHTML](https://github.com/toss/slash/blob/main/packages/common/utils/src/escapeHTML.ts).
=> feat(@toss/utils): Translate tests codes for `escapeHTML` and update docs to match parameter name

packages/react/react/src/utils/index.ts
Added `/** @tossdocs-ignore */` in index.ts to exclude from document generation.
`react/src/utils/index.ts` file is collected for document generation.
So the index file is visible from docs.
But this file has no meaningful content.
link for index file in docs- [link](https://slash.page/ko/libraries/react/react/src/utils/index.ts.tossdocs)
=> chore(@toss/react): Add @tossdocs-ignore symbol in react/src/utils/index.ts

packages/react/react/src/hooks/usePreservedCallback.spec.ts
This PR adds tests for the `usePreservedCallback` hook:
1. Checks if the hook returns updated values after state changes.
2. Ensures the callback reference is constant after state updates.
3. Verifies that arguments are correctly passed to the callback.
[ AS-IS ]
❌
[ TO-BE ]
=> test(@toss/react): Add usePreservedCallback test code

packages/react/redirect/src/base/boundary/RedirectionBoundary.en.md, packages/react/redirect/src/base/boundary/RedirectionBoundary.ko.md, packages/react/redirect/src/base/boundary/RedirectionBoundary.tsx
The RedirectionBoundary component is not documented, so I documented it in ko and en.
=> docs(@toss/redirect): add documentation for RedirectionBoundary

configs/rollup/package.json, package.json, packages/common/assert/package.json, packages/common/crypto/package.json, packages/common/date/package.json, packages/common/hangul/package.json, packages/common/ky/package.json, packages/common/sentry/package.json, packages/common/storage/package.json, packages/common/utility-types/package.json, packages/common/utils/package.json, packages/common/validators/package.json, packages/react/a11y/package.json, packages/react/async-boundary/package.json, packages/react/async-stylesheet/package.json, packages/react/emotion-utils/package.json, packages/react/error-boundary/package.json, packages/react/framer-motion/package.json, packages/react/impression-area/package.json, packages/react/lottie/package.json, packages/react/react-query/package.json, packages/react/react/package.json, packages/react/recoil/package.json, packages/react/redirect/package.json, packages/react/scroll-animation/package.json, packages/react/use-funnel/package.json, packages/react/use-loading/package.json, packages/react/use-overlay/package.json, packages/react/use-query-param/package.json
Add the repository information to package.json. Developers who want to see the live code of the library can access toss slash github directly from this repository information. Various tools support the command, including git command and vscode extension
Reference Link
- [npm package json - repository field](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository)
=> chore: add repository information in package.json

packages/common/utils/src/device/isAndroid.ts, packages/common/utils/src/device/isIOS.ts, packages/common/utils/src/device/isMacOS.ts
This PR includes changes in 
- `@toss/utils/device/isAndroid.ts`
- `@toss/utils/device/isIOS.ts`
- `@toss/utils/device/isMacOS.ts`
Since `String.prototype.match()` function only returns an `Array`or `null`, there's no need of using [inequality operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Inequality) instead of [strict inequality operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_inequality).
To prevent future type-related issues, using strict inequality operator should be recommended.
=> fix(@toss/utils): change inequality operator to strict inequallity operator

packages/common/storage/src/typed/factory.ts, packages/common/storage/src/typed/storages/TypedStorage.spec.ts, packages/common/storage/src/typed/storages/TypedStorage.ts
Fixes https://github.com/toss/slash/issues/428 and added test code.
Basically, I've changed the generic type `T` to `T extends boolean ? boolean : T`
- [✅] I read and included theses actions below
=> fix(@toss/storage): Fix boolean type inference for TypedStorage 

packages/react/react/src/hooks/useInterval.spec.tsx
Changed Korean to English for useInterval Hook and improved coverage.
[AS-IS]
[TO-BE]
=> test(@toss/react): useInterval hook test, changed to English, improved scope

packages/common/utils/src/loadScript.spec.ts
I wrote test code for the loadScript function
[AS-IS]
[TO-BE]
=> test(@toss/utils): Add new test for loadScript

packages/common/utils/src/device/isServer.ts
This PR makes two changes:
1. Removed `typeof global !== 'undefined'` according to [this issue](https://github.com/toss/slash/issues/352#issue-1953691398) and [this conversation](https://github.com/suspensive/react/pull/239#discussion_r1365379813)
2. Added `'Deno' in globalThis;`. [Tanstack/query](https://github.com/TanStack/query/blob/2ddf8036360279fcd6e3567859ec9c68fbfc024a/packages/query-core/src/utils.ts#L65) and [vercel/swr](https://github.com/vercel/swr/blob/cd22c46c4a0977e9d9afcd7b23f629e56e729344/src/_internal/utils/env.ts#L6) now use this checking for `isServer`. And we should use `globalThis` instead of `window` because it [became deprecated in Deno](https://github.com/denoland/deno/pull/22057).
- [✅] I read and included theses actions below
1. I have read the [Contributing …
=> fix(@toss/utils): Add 'Deno' in globalThis for isServer()

packages/common/utils/src/Numbers.spec.ts
'Uncovered line' has been added due to [changed code](https://github.com/toss/slash/pull/371/files#diff-8bcab93973b45d4060faa3f177cfbf408f541e314a52d915b6608345e97952db). So I improved it.
[ AS-IS ]
[ TO-BE ]
=> test(@toss/utils): improve test for formatToKoreanNumber

packages/common/utils/src/device/isAndroid.ts, packages/common/utils/src/device/isIOS.ts
Some packages are missing the @tossdocs-ignore, resulting in unnecessary pages.
- [isAndroid](https://slash.page/ko/libraries/common/utils/src/device/isAndroid.ts.tossdocs)
- [isIOS](https://slash.page/ko/libraries/common/utils/src/device/isIOS.ts.tossdocs)
=> docs(@toss/utils): Added missing `@tossdocs-ignore` comment

packages/react/emotion-utils/src/spacing.en.md, packages/react/emotion-utils/src/spacing.ko.md, packages/react/emotion-utils/src/spacing.tsx
SpacingProps: Replace `never` with `Omit` for children
=> refactor(@toss/emotion-utils): SpacingProps: Replace `never` with `Omit` for children

packages/react/react/src/hooks/useInterval.ts, packages/react/react/src/hooks/usePreservedCallback.ts, packages/react/react/src/hooks/useTimeout.ts, packages/react/react/src/hooks/useVisibilityEvent.ts
We can use `usePreservedCallback` to keep a reference to the callback function and ensure that it is up to date. 
=> refactor(@toss/react): change to using usePreservedCallback

packages/react/react/src/hooks/useLocalStorageChangeDetector.spec.tsx
A test code has been created to validate the behavior of the useLocalStorageChangeDetector.
=> test(@toss/react): wrote test code for useLocalStorageChangeDetector

packages/common/utils/src/device/isClient.spec.ts
1. Add isClient's test code.
[ AS-IS ]
[ TO-BE ]
=> test(@toss/utils): Add new test for isClient

docs/i18n/ko/docusaurus-plugin-content-pages/index.md
|<img width="888" alt="image" src="https://github.com/toss/slash/assets/39869096/d436ca7f-67c5-40b8-9025-d0243c7f3045">|<img width="1102" alt="image" src="https://github.com/toss/slash/assets/39869096/41082ca9-d369-475e-858a-15bc31f3e693">|
|---|---|
| Broken link | Clicked `@toss/react` link |
- updated broken link 🔗
=> docs: fix broken link in KR documentation

packages/react/react/src/components/OutsideClick/OutsideClick.en.md, packages/react/react/src/components/OutsideClick/OutsideClick.ko.md, packages/react/react/src/components/OutsideClick/OutsideClick.test.tsx, packages/react/react/src/components/OutsideClick/OutsideClick.tsx, packages/react/react/src/components/OutsideClick/index.ts, packages/react/react/src/components/index.ts
```jsx
const [wrapperEl, setWrapperEl] = useState(null);
useOutsideClickEffect(wrapperEl, () => {
console.log('outside clicked!');
});
return <div ref={setWrapperEl}></div>;
```
```jsx
<OutsideClick callback={() => console.log('outside clicked!')}>
<div>something</div>
</OutsideClick>
```
<br/>
A component that declaratively handles the functionality of `useOutsideClickEffect`.
If you click outside the component wrapped in `OutsideClick`, `callback` is executed.
```jsx
<OutsideClick callback={callback}>{children}</OutsideClick>
```
Assign an generic `ElementType` to `<OutsideClick>`.
Use `HTMLAttributes` as needed.
```jsx
function Component() {
return (
<OutsideClick<'input'>
callback={() => console.log('outside clicked')}
as="input"
disabled
/>
);
}
```
<br/>
<br/>
1. I have read the …
=> feat(@toss/react): OutsideClick Component

packages/react/react/src/hooks/useOutsideClickEffect.ts
```jsx
useEffect(() => {
containers.current = (Array.isArray(container) ? container : [container]).filter(isNotNil);
}, [container]);
```
```jsx
useEffect(() => {
document.addEventListener('click', handleDocumentClick);
document.addEventListener('touchstart', handleDocumentClick);
return () => {
document.removeEventListener('click', handleDocumentClick);
document.removeEventListener('touchstart', handleDocumentClick);
};
}, []);
```
<br/>
```jsx
useEffect(() => {
containers.current = [container].flat(1).filter(isNotNil);
}, [container]);
```
```jsx
useEffect(() => {
document.addEventListener('click', handleDocumentClick);
document.addEventListener('touchstart', handleDocumentClick);
return () => {
document.removeEventListener('click', handleDocumentClick); …
```
=> fix(@toss/react): improve readability and add dependencies `useOutsideClickEffect`

packages/react/emotion-utils/package.json, packages/react/emotion-utils/src/FullHeight.tsx
Replace the `useIsomorphicLayoutEffect` previously declared in the component with a custom hook implemented in **@toss/react**.
=> fix(@toss/react): FullHeight component change hook

packages/react/react/src/hooks/useStorageState.spec.ts, packages/react/react/src/hooks/useStorageState.ts
Fixed #477
Fix useStorageState hook where state updates are not properly synchronized across components. 
issue detail: When a value is initialized  until the set function is explicitly called. Additionally, invoking the refresh method in one component does not update the state in other components using the same storage key.
=> fix(@toss/react): @toss/react State synchronization issue in useStorageState

docs/i18n/en/docusaurus-theme-classic/footer.json, docs/i18n/ko/docusaurus-theme-classic/footer.json
copyright year is fixed because of i18n footer options.
remove these options so that copyright year would be current year.
=> chore: remove footer i18n on docusaurus-theme-classic

packages/react/use-funnel/src/Funnel.tsx, packages/react/use-funnel/src/models.ts, packages/react/use-funnel/src/useFunnel.tsx
NonEmptyArray type already exists in @toss/util. However, a readonly property has been added to the existing NonEmptyArray type with the same name in model.ts. Although they have the same name, they have additional properties, which can cause confusion.
- The NonEmptyArray type, which was referenced in many places, has been abstracted into StepType.
- StepType can perform the same type inference as before.
=> fix(use-funnel): Fix NonEmptyArray type in model.ts.

packages/react/react/src/hooks/useOutsideClickEffect.ts
Fixes https://github.com/toss/slash/issues/354 and https://github.com/toss/slash/issues/449
I agree with [this answer](https://github.com/toss/slash/pull/355#issuecomment-1873193681). `click` event works fine on touchable screen too, so there is no need to have a `touch` event listener.
I believe another solution might be adding `e.preventDefault()` for the `touch` event. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events):
> ... [event.preventDefault()](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) to keep the browser from continuing to process the touch event (this also **prevents a mouse event from _also_ being delivered**).
However, I think this is a bit more over-engineering... so I decided to go with the first solution.
- [✅] I …
=> fix(@toss/react): useOutsideClickEffect is called twice on touch event

packages/common/storage/src/safeLocalStorage.ko.md, packages/common/storage/src/safeSessionStorage.ko.md, packages/common/storage/src/typed/createTypedLocalStorage.ko.md, packages/common/storage/src/typed/createTypedSessionStorage.ko.md, packages/common/storage/src/typed/storages/NumberTypedStorage.ko.md
Hello, While studying the slash `@toss/storage` functions, I encountered broken links in the Korean documentation for the `@toss/storage` library. 
This fixes these broken links caused by misspellings that resulted in `Page Not Found` errors. The following corrections have been made to ensure proper navigation.
- `generatestorage` -> `generateStorage`
- `generatesessionstorage` -> `generateSessionStorage`
- `typedstorage` -> `TypedStorage`
=> docs(@toss/storage): fix broken links in Korean documentation for storage functions

packages/react/react/src/hooks/useInterval.en.md, packages/react/react/src/hooks/useInterval.ko.md, packages/react/react/src/hooks/useInterval.spec.tsx, packages/react/react/src/hooks/useInterval.ts
When using Interval, sometimes you need to stop and resume the interval.
When configuring the carousel, if auto-turning is implemented through useInterval, the interval must be stopped when the user is in the middle of the slide, and the interval must be resumed when the slide is completed.
In this case, I suggest that if it returns the factors presented above in the hook, it will be easy to implement!
Accordingly, why don't you return the stop, resume function, and intervalRunning status.
=> feat(@toss/react): useInterval stop/resume support

packages/react/react/src/hooks/useInterval.en.md, packages/react/react/src/hooks/useInterval.ko.md
While checking the docs with the previous PR(#476) applied, I noticed a typo in the Korean document that I had missed before, so I corrected it. Additionally, I standardized the wording in the English docs.
I apologize for any inconvenience caused by my oversight.
=> docs(@toss/react): useInterval korean docs fix typo

packages/common/utils/src/Masker.ts
When using regular expressions to determine Korean characters, we are using [가-힣]. However, in the maskExceptForEdge method, the library is using “힇”. '힣's unicode value is more higher than '힇'. So if you want to contain whole hangul, you should use '힣'
Fix the typo and send a PR. 
=> fix(@toss/utils): replace 힇 to 힣

packages/react/use-query-param/src/hooks/useNextRouter.ts, packages/react/use-query-param/src/utils/waitForRouterReady.ts
When i tried to use @toss/use-funnel, i got a error `Cannot find module next/router`
I found that `@toss/use-funnel`  depended on `@toss/use-query-param` and fixed it by adding the extension.
My Next version is v13 and i found a similar case that fixed this issue in [@toss/use-funnel](https://github.com/toss/slash/pull/312/files#diff-22b2ba85b7dc35c45d33851a75ae5751fa89db39d5776559c02b086baaa26168). 
=> fix(@toss/use-query-param): add extenion .js to import next/router

README-ko_kr.md, README.md
Add information about [suspensive](https://github.com/toss/suspensive), which has now joined the Toss organization, to the Project Status section of the README.
Also, update the location of the links to the package repositories.
=> docs: Add suspensive to Project Status in README

docs/i18n/ko/docusaurus-plugin-content-pages/index.md, docs/pages/index.md
- I hope that by adding a "Project Status" section to the main page of Slash, interest in Slash will extend to other Toss libraries, fostering ecosystem development and encouraging active contributions.
- When searching for "Toss library" on Google, Slash appears at the top of the results. It would be ideal if this could also lead users to other Toss libraries.
| AS-IS | TO-BE |
| --- | --- |
|<img width="896" alt="image" src="https://github.com/user-attachments/assets/1b72d1c7-01f2-4f82-a092-ddd7eba9af57" />|<img width="899" alt="image" src="https://github.com/user-attachments/assets/5df7cfa0-7d45-4e63-b6c3-1895fb2f313b" />|
=> docs: add project status section

packages/react/use-funnel/README.ko.md
Fix an issue where migration guide link on the `use-funnel` page
=> fix(use-funnel): fix invalid URL in migration guide
